package Rdiffopke::Exception;

use Exception::Class (
    Rdiffopke::Exception => { description => 'generic Rdiffopke exception', },

    Rdiffopke::Exception::Signal => {
        isa         => 'Rdiffopke::Exception',
        description => 'Rdiffopke exception generated by signal',
        fields      => ['signal'],
    },

    Rdiffopke::Exception::BadParams => {
        isa         => 'Rdiffopke::Exception',
        description => 'User supplied wrong parameters or input to start program',
    },

);

1;

